#!/usr/bin/env python
"""Generate a strong password.

Usage: strongpw (-h | --help)
       strongpw (-v | --version)
       strongpw [--no-punctuation]
       strongpw [--no-punctuation] <n>
       strongpw [-r <n>] [-l <n>] [--no-punctuation]

Options:
 -v --version          Version of the program.
 -h --help             Show this screen.
 -r --repeat <n>       Create strong passwords n-time one per line [default: 1].
 -l --length <n>       Length of password to be created [default: 12].
 -p --no-punctuation   Create password without punctuation strings [default: false].

Example:
 # create a strong 20 character password.
 strongpw 20 

 # create a not so strong password most services will accept.
 strongpw 20 --no-punctuation

 # create very strong passwords for 500 "friends" on social media.
 strongpw -r 500 -l 30

"""

from random import choice
from docopt import docopt
import string
import sys
import re


def generate_password(length=12, chars=None):
    """
    Return a fixed length string suitable as a password, based on 
    a randomized default or given character set.
    """
    if not chars:
        chars = string.letters + string.digits + string.punctuation + " "

    # http://www.cs.duke.edu/~ola/patterns/plopd/loops.html#loop-and-a-half
    while True:
        strongpw = ''.join([choice(chars) for i in xrange(length)])
        # we do not allow consecutive chars
        if not re.findall(r"(.)\1\1", strongpw):
            break
    return strongpw


def main(docargs):
    """Dispatch the work based on arguments."""
    chars = None
    password_length = int(docargs['<n>'] or docargs['--length'])

    # http://blog.codinghorror.com/your-password-is-too-damn-short/
    if password_length < 12:
        raise ValueError('Your password is too damn short.')

    if docargs['--no-punctuation']:
        chars = string.letters + string.digits + " "

    for i in xrange(int(docargs['--repeat'])):
        print generate_password(password_length, chars)


if __name__ == "__main__":
    sys.exit(main(docopt(__doc__, version='strongpw 1.0')))
